openai-api-base: https://api.githubcopilot.com

# model: openai/gpt-4.1
model: openai/claude-sonnet-4
# model: openai/gemini-2.5-pro
# model: openai/claude-3.7-sonnet-thought
# model: openai/o4-mini-2025-04-16

weak-model: openai/gpt-4o-mini
show-model-warnings: false
disable-playwright: false
playwright-proxy: "socks5://127.0.0.1:10808"
auto-commits: false
add-gitignore-files: true
